version: "2"

services:
  php-apache:
    build:
      context: .
      dockerfile: .docker/php-apache/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - laravel

networks:
  laravel: